"""mkdocs hook: inject `<cmd> --help` into commands.md at build time.

Replaces the placeholder `{{ cli_reference }}` in docs/commands.md with one
fenced ```text``` block per subcommand, generated by invoking the parser
defined in src/reflect/cli.py. Mirrors agents-cli's docs/hooks pattern.
"""

from __future__ import annotations

import argparse
import io
from typing import Any


def on_page_markdown(
    markdown: str, page: Any, config: Any, files: Any
) -> str:
    if "{{ cli_reference }}" not in markdown:
        return markdown

    from reflect.cli import build_parser

    parser = build_parser()
    sections: list[str] = []

    # Top-level help
    sections.append("## `reflect`\n")
    sections.append("```text")
    sections.append(parser.format_help().rstrip())
    sections.append("```\n")

    # Per-subcommand help
    subparsers_actions = [
        a for a in parser._actions if isinstance(a, argparse._SubParsersAction)
    ]
    for action in subparsers_actions:
        for name, subparser in sorted(action.choices.items()):
            sections.append(f"## `reflect {name}`\n")
            buf = io.StringIO()
            subparser.print_help(file=buf)
            sections.append("```text")
            sections.append(buf.getvalue().rstrip())
            sections.append("```\n")

    return markdown.replace("{{ cli_reference }}", "\n".join(sections))
